In [1]:
import pandas as pd
from sqlalchemy import create_engine, text

engine = create_engine("sqlite:///../data/fred_data.db")

In [2]:
query = """
SELECT COUNT(*) AS total_rows,
       MIN(date) AS earliest_date,
       MAX(date) AS latest_date
FROM macro_series;
"""
pd.read_sql(text(query), con=engine.connect())

   total_rows               earliest_date                 latest_date
0        2282  1990-01-01 00:00:00.000000  2026-06-11 00:00:00.000000

In [3]:
query = """
SELECT *
FROM macro_series
ORDER BY date DESC
LIMIT 10;
"""
pd.read_sql(text(query), con=engine.connect())

,date,fed_funds_rate,commercial_loans,consumer_credit,mortgage_rate_30yr,credit_card_delinquency,cpi
0,2026-06-11 00:00:00.000000,NaN,NaN,None,6.52,None,NaN
1,2026-06-04 00:00:00.000000,NaN,NaN,None,6.48,None,NaN
2,2026-05-28 00:00:00.000000,NaN,NaN,None,6.53,None,NaN
3,2026-05-21 00:00:00.000000,NaN,NaN,None,6.51,None,NaN
4,2026-05-14 00:00:00.000000,NaN,NaN,None,6.36,None,NaN
5,2026-05-07 00:00:00.000000,NaN,NaN,None,6.37,None,NaN
6,2026-05-01 00:00:00.000000,3.63,2897.1752,None,NaN,None,333.979
7,2026-04-30 00:00:00.000000,NaN,NaN,None,6.30,None,NaN
8,2026-04-23 00:00:00.000000,NaN,NaN,None,6.23,None,NaN
9,2026-04-16 00:00:00.000000,NaN,NaN,None,6.30,None,NaN

In [4]:
query = """
SELECT
    COUNT(*) AS total_rows,
    SUM(CASE WHEN fed_funds_rate IS NULL THEN 1 ELSE 0 END) AS missing_fed_funds,
    SUM(CASE WHEN consumer_credit IS NULL THEN 1 ELSE 0 END) AS missing_consumer_credit,
    SUM(CASE WHEN commercial_loans IS NULL THEN 1 ELSE 0 END) AS missing_commercial_loans,
    SUM(CASE WHEN mortgage_rate_30yr IS NULL THEN 1 ELSE 0 END) AS missing_mortgage_rate
FROM macro_series;
"""
pd.read_sql(text(query), con=engine.connect())

,total_rows,missing_fed_funds,missing_consumer_credit,missing_commercial_loans,missing_mortgage_rate
0,2282,1845,1846,1845,380

In [5]:
query = """
SELECT
    CAST(SUBSTR(date, 1, 3) AS INTEGER) * 10 AS decade,
    ROUND(AVG(fed_funds_rate), 2) AS avg_rate,
    ROUND(MAX(fed_funds_rate), 2) AS peak_rate,
    ROUND(MIN(fed_funds_rate), 2) AS trough_rate
FROM macro_series
WHERE fed_funds_rate IS NOT NULL
GROUP BY decade
ORDER BY decade;
"""
pd.read_sql(text(query), con=engine.connect())

   decade  avg_rate  peak_rate  trough_rate
0    1990      5.15       8.29         2.92
1    2000      2.96       6.54         0.12
2    2010      0.61       2.42         0.07
3    2020      2.81       5.33         0.05